### ISSUE TITLE
Dropdown feature with proof

### ISSUE THREAD

**Issue by aburousan** [RaphaelArkadyMeyerNYU/Ram900Hosting#1]
I was checking FranklinTheorem.jl and came across your personal website. I just want to ask is there a way to use the dropdown feature of the proof?
The proof is not working and also whatever I write inside the dropdown it is showing not matter if i click the button or not.

**Comment by RaphaelArkadyMeyerNYU** [comment]
Hi there!

Yeah the dropdown doesn't have anything to do with the proof environment really. You can use it without a proof. For instance, I do this on line 59 of `index.md`.

Without seeing your code, it would be hard for me to debug, but I'd make sure that you have `\theoremscripts` at the end of your markdown file (like on line 355 of `index.md`). That invokes the javascripts needed to make the dropdowns menus work.

**Comment by aburousan** [comment]
Sorry... here is the code other commands works but not the dropdown.
![Screencast from 12-03-24 10_28_08 PM IST](https://github.com/RaphaelArkadyMeyerNYU/Ram900Hosting/assets/60939745/9722e0b3-bb34-4773-9e63-e00b132c6dee)
As you can see in the gif, lemma is working fine but not the dropdown. I have followed the steps for using Franklintheorem

**Comment by RaphaelArkadyMeyerNYU** [comment]
Ah okay, I think I see what's going on. I am assuming/inferring that you're not importing the CSS file for franklinTheorems.

The way that the text in a dropdown is hidden is using CSS. In particular, the CSS file for franklinTheorems.jl is designed around looking good in the `tufte` theme in Franklin. In order for the hidden text to appear and disappear, you will need to have some CSS styled to how you want your webpage to look.

I would really recommend using the default CSS file as a starting point ([link](https://github.com/RaphaelArkadyMeyerNYU/FranklinTheorems.jl/blob/main/src/FranklinTheorems.css)) and just adjusting the numbers and colors to match your webpage, but if all you want is for clicking to cause the dropdown to show/hide, then I believe all you need to do is the following css:

```css
/* Style the accordion panel. Note: hidden by default */
.franklin-content .theorem-panel {
  padding: 0 0.5em;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.4s ease-out;
}
```

The `max-height: 0` makes the drop-down's subject matter fall outside of the bounding box. The `overflow: hidden` makes anything outside of the bounding box not rendered. The `transition` and `padding` are purely aesthetic recommendations.

**Comment by aburousan** [comment]
Thank you but just a very foolish question, where I should add that line which you have written?, 
Those are already there inside .CSS file. 
When I important FranklinTheorem, shouldn't they just get imported automatically?

**Comment by RaphaelArkadyMeyerNYU** [comment]
No, the CSS isn't imported automatically. You can find the default CSS file by running these commands though:
```julia
using FranklinTheorems
FranklinTheorems.css_path()
```
But it wouldn't make a lot of sense to force other people to use my exact CSS files unchanged, since my CSS was written to achieve a specific look on the tufte theme. Other people will likely want other looks, and you should make and edit your own CSS file to achieve that.

Though, my provided CSS file should get you a good distance of the way there.

To add an additional CSS file to your franklin environment, add the CSS file to the `\_css` directory and add a line to `\_layout\style.html` to include the CSS file on all of your webpages.

**Comment by aburousan** [comment]
Thank you.... Finally got it.
